url: "https://lasdesistemas.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/lds" # the subpath of your site, e.g. /blog
title: "Las de Sistemas" # the name of your site, e.g. ACME Corp.
description: ""
keywords: ""

lang: 'es'
